[package]
name = "neurotraffic_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
ndarray = "0.15"
rayon = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"
regex = "1.8"
ordered-float = "3.7"
indicatif = "0.17"
